### ISSUE TITLE
该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

### ISSUE THREAD

**Issue by askintution** [FunctionFun/zhihu-plus#1]
安装后显示：
该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

无法启用这个插件
chrome已开开发者模式

**Comment by FunctionFun** [comment]
**无法启用的原因**：由于 google 禁止了非应用商店插件，这里没有提交到chrome的官方应用商店，所以不能直接用 crx 文件安装，因此只能在国产 chrome 浏览器如 360 极速浏览器等软件使用 crx 方式安装。

**解决方法**：1. 选择 【加载已解压的扩展程序 → 选择 dist 目录】方式安装；2. 或者使用国产 chrome 浏览器。
